@urlV1 = http://localhost:3000/api/v1

POST {{urlV1}}/auth/signup
content-type: "application/json"

{
	"name": "testName1",
	"email": "sample1@example.com",
	"password": "123"
}

> {%
	client.global.set('TOKEN', response.body.token);
%}

###

POST {{urlV1}}/auth/login
content-type: application/json

{
	"email": "sample1@example.com",
	"password": "123"
}

> {%
	client.global.set('TOKEN', response.body.token);
%}

###

POST {{urlV1}}/auth/logout
accept: application/json
Cookie: token={{TOKEN}}

###

GET {{urlV1}}/auth/test?email=sample1@example.com
accept: application/json

###

GET {{urlV1}}/admin/test
Cookie: token={{TOKEN}}

###

PUT {{urlV1}}/admin/users/promote
Cookie: token={{TOKEN}}
content-type: application/json

{
	"role": "admin",
	"email": "sample2@example.com"
}

###

GET {{urlV1}}/books/
accept: application/json

###

GET {{urlV1}}/books/search?q=i
accept: application/json
