// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"database/sql"

	"github.com/google/uuid"
)

type Author struct {
	ID       uuid.UUID
	FullName string
}

type Book struct {
	ID              uuid.UUID
	Name            string
	Score           sql.NullFloat64
	PublicationDate sql.NullString
	TypeID          uuid.UUID
	AuthorID        interface{}
	PublisherID     interface{}
}

type ListItem struct {
	UserEmail string
	BookID    uuid.UUID
	Status    int64
}

type Publisher struct {
	ID   uuid.UUID
	Name string
}

type Type struct {
	ID   uuid.UUID
	Name string
}

type User struct {
	Email        string
	Name         string
	Role         string
	RoleSetBy    sql.NullString
	PasswordHash string
}
